spring:
  application:
    name: StockVault

  datasource:
    url: jdbc:postgresql://localhost:5432/stockvault
    username: stockvault
    password: stockvault

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true