spring:
  application:
    name: StockVault

  profiles:
    active: dev

  datasource:
    url: ${ DB_URL:jdbc:postgresql://localhost:5432/stockvault}
    username: ${ DB_USERNAME:stockvault}
    password: ${ DB_PASSWORD:stockvault}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      secret: ${ JWT_SECRET:super-puper-secret-key-32-bytes-minimum}

massive:
  api:
    base-url: https://api.massive.com
    key: ${ API_KEY:km54pJSTUeOrgyX6pVPuqW0zw5ZjVTQg}